# -*- coding: utf-8 -*-
"""Module 1.2 - Introduction to Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THP8AtFq-OHmBB81lT8VX7RTRbcDcLT-

Contents

1. Reading data as excel file and csv

Reading dataset from GitHub using requests
"""

# !pip install requests

import pandas as pd
import requests
from io import StringIO

"""Here, the requests.get() function is used to send an HTTP GET request to the specified URL. This function returns a Response object, and you've assigned it to the variable response. This object contains the server's response to the request."""

url = 'https://github.com/Adithi-27/Pandas-for-Data-Science-/blob/main/bike.csv'
response = requests.get(url)

"""The StringIO class from the io module is used to create a file-like object from the text content of the response. response.text contains the content of the CSV file as a string, and StringIO helps to treat this string as a file-like object that pd.read_csv can read."""

csv_content = StringIO(response.text)

!pip install pandas requests

import io
import requests
import pandas as pd

# Fetch raw CSV data from GitHub
url = 'https://raw.githubusercontent.com/Adithi-27/Pandas-for-Data-Science-/main/bike.csv' # Changed to raw content URL
response = requests.get(url)

# Decode the content and create a StringIO object
csv_content = io.StringIO(response.content.decode('utf-8'))

# Read the CSV data into a pandas DataFrame, specify delimiter and error handling
df = pd.read_csv(csv_content, sep=',', on_bad_lines='skip') # Added sep=',' and on_bad_lines='skip'

# Display the first few rows of the DataFrame
df.head()

df.info()

df.shape

"""Reading dataset from GitHub using web get"""

pip install wget

import wget

# Replace the URL with the raw URL of your CSV file on GitHub
url = 'https://github.com/Adithi-27/Pandas-for-Data-Science-/blob/main/bike.csv'

# Use wget to download the CSV file
file_path = wget.download(url)

!pip install wget
import wget
import pandas as pd

# Replace the URL with the raw URL of your CSV file on GitHub.
# Important: The raw URL should end with .csv
# like this https://raw.githubusercontent.com/Adithi-27/Pandas-for-Data-Science-/main/bike.csv
url = 'https://raw.githubusercontent.com/Adithi-27/Pandas-for-Data-Science-/main/bike.csv'

# Use wget to download the CSV file
file_path = wget.download(url)

# Use pd.read_csv to read the CSV data into a Pandas DataFrame
df = pd.read_csv(file_path)

df.shape

df.head()

df.shape

"""Reading dataset from GitHub using direct raw data URL"""

# Correct URL to raw content on GitHub
url = 'https://raw.githubusercontent.com/Adithi-27/Pandas-for-Data-Science-/main/bike.csv'

df = pd.read_csv(url)

df.head()

df.shape

"""Reading Data From CSV/Excel

1.   XLSX (Excel Workbook): This is a binary file format associated with Microsoft Excel. It can store multiple sheets with formatting, formulas, charts, and images.
2. CSV (Comma-Separated Values): This is a plain text file where values are separated by commas. It contains only the data without any formatting, formulas, or other elements.
"""

import pandas as pd
df = pd.read_csv('/content/bike.csv', sep=';')
df