# -*- coding: utf-8 -*-
"""Module 1.4 - Introduction to Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140scC6tMLHEDlHFRIJcyLLc9tcDoA0Y5

Contents

1. Delete Columns
2. Delete Rows & loc, iloc
3. Rename Columns
"""

import pandas as pd
df = pd.read_csv('/content/Screen Time Data.csv')
df.head()

"""Delete Columns Using 'del' Statement"""

del df['index']

df.head()

"""Delete Columns Using 'pop' method"""

df.pop('Week Day').head()

df.head()

"""Delete Columns Using 'loc' and 'iloc' method"""

df = df.loc[:, ['Total Screen Time ','Social Networking','Reading and Reference','Productivity']]
df.head()

df = df.loc[[1,2,3,4], ['Total Screen Time ','Social Networking','Reading and Reference','Productivity']]
df.head()

df = df.iloc[:, [0,1]]
df

"""Delete Columns Using 'drop' method"""

import pandas as pd
df = pd.read_csv('/content/Screen Time Data.csv')
df.head()

#df = df.drop('index', axis=1)
df.drop('index', axis=1, inplace=True)

df.head()

df.drop(columns=['Week Day', 'Social Networking'])

df.drop(['Date','Other'], axis=1, inplace=True)

df

x = df.drop('Yoga', axis=1)

x.head()

y = df[['Yoga']]

y.head()

"""Drop the Rows in Pandas"""

import pandas as pd
df = pd.read_csv('/content/Screen Time Data.csv')
df.head()

df.drop([0,1]).head()

df.drop([0,1], axis='index')

df = df[df['Productivity']>15]
df.head()

import pandas as pd
df = pd.read_csv('/content/Screen Time Data.csv')
df.head()

"""Rename & Concate DataFrame"""

df1 = pd.DataFrame({'AGE': [16, 20], 'INCOME': [3000, 4000]})
df2 = pd.DataFrame({'AGE': [25, 26], 'INCOME': [7000, 8000]})

df1

df2

df1 = df1.rename(columns={'AGE': 'age', 'INCOME': 'income'})
df2 = df2.rename(columns={'AGE': 'age', 'INCOME': 'income'})

df1

df2

result = pd.concat([df1, df2])
result

result = pd.concat([df1, df2], axis=1)
result